переписала пайплайн

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,33 +5,101 @@ on:
     branches: [master, stage, dev]
 
 jobs:
-  deploy:
+  build-and-push:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
+      - name: Set API URLs from secrets
+        id: set-urls
+        run: |
+          if [ "${GITHUB_REF_NAME}" = "main" ]; then
+            echo "api_url=${{ secrets.API_URL_PROD }}" >> $GITHUB_OUTPUT
+          elif [ "${GITHUB_REF_NAME}" = "dev" ]; then
+            echo "api_url=${{ secrets.API_URL_DEV }}" >> $GITHUB_OUTPUT
+          elif [ "${GITHUB_REF_NAME}" = "stage" ]; then
+            echo "api_url=${{ secrets.API_URL_DEV }}" >> $GITHUB_OUTPUT
+          else
+            echo "api_url=${{ secrets.API_URL_TEST }}" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build and push image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crm-frontend:${{ github.sha }}
+          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/crm-frontend:cache
+          cache-to: type=inline
+          build-args: |
+            REACT_APP_API_URL=${{ steps.set-urls.outputs.api_url }}
+            REACT_APP_ID=${{ secrets.APP }}
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build-and-push
+    steps:
       - name: Setup SSH
         uses: webfactory/ssh-agent@v0.5.3
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      - name: Deploy to Production
-        if: github.ref_name == 'master'
-        run: ssh -o StrictHostKeyChecking=no -t ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd apps/crm-frontend && git pull origin master && docker compose down  && docker compose up --build -d"
+      - name: Determine Deployment Path and Tag
+        run: |
+          if [[ "${{ github.ref_name }}" == "master" ]]; then
+            echo "DEPLOY_PATH=apps/crm-frontend" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
+            echo "DEPLOY_PATH=apps/crm-frontend-dev" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "stage" ]]; then
+            echo "DEPLOY_PATH=apps/crm-tiacore-frontend-stage" >> $GITHUB_ENV
+          else
+            echo "❌ Неизвестная ветка! Прерываем процесс."
+            exit 1
+          fi
+          echo "DEPLOY_TAG=${{ github.sha }}" >> $GITHUB_ENV
 
-      - name: Deploy to Development
-        if: github.ref_name == 'dev'
-        run: ssh -o StrictHostKeyChecking=no -t ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd apps/crm-frontend-dev && git pull origin dev && docker compose down && docker compose up --build -d"
-      - name: Deploy to Stage
-        if: github.ref_name == 'stage'
-        run: ssh -o StrictHostKeyChecking=no -t ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd apps/crm-tiacore-frontend-stage && git pull origin stage && docker compose down && docker compose up --build -d"
+
+      - name: Deploy client
+        run: |
+          echo "🚀 Деплой..."
+          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
+            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
+            export DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}
+            export DEPLOY_TAG=${{ github.sha }}
+            export DEPLOY_BRANCH=${GITHUB_REF##*/}
+
+            cd $DEPLOY_PATH || { echo "❌ Не удалось перейти в $DEPLOY_PATH"; exit 1; }
+
+            echo "\$DOCKERHUB_TOKEN" | docker login -u "\$DOCKERHUB_USERNAME" --password-stdin \
+              || { echo "❌ Docker login failed"; exit 1; }
+
+            docker pull \$DOCKERHUB_USERNAME/crm-frontend:\$DEPLOY_TAG \
+              || { echo "❌ Docker pull failed"; exit 1; }
+
+            if [ ! -f .env ]; then touch .env; fi
+            grep -q "^TAG=" .env && sed -i "s/^TAG=.*/TAG=\$DEPLOY_TAG/" .env || echo "TAG=\$DEPLOY_TAG" >> .env
+
+            docker compose pull --quiet --ignore-pull-failures &&
+            docker compose up -d --remove-orphans \
+              || { echo "❌ docker compose up failed"; exit 1; }
+          EOF
+
+
 
   notify:
     name: 📬 Telegram Notify
     runs-on: ubuntu-latest
-    needs: [deploy]
+    needs: [build-and-push,deploy]
     if: always()
     steps:
       - name: 📬 Telegram Notification
@@ -46,7 +114,7 @@ jobs:
 
           if [ "$DEPLOY_STATUS" != "success" ]; then
             STATUS="🛑 *Ошибка деплоя*"
-            EXTRA_LINK="\n\n[🔍 Открыть GitHub Actions]($RUN_URL)"
+            EXTRA_LINK="[🔍 Открыть GitHub Actions]($RUN_URL)"
           else
             STATUS="✅ Деплой *успешен*"
             EXTRA_LINK=""
